#!/bin/bash
echo ""
clear
echo ""
echo -e ""
echo ""
echo ""
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ----------------------------------------  \e[1;91m\e[0m'
echo -e $'\e[1;91m\e[0m\e[1;33m\e[0m\e[1;90m\e[0m\e[1;92m  !!       New Tool     !!\e[0m'
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ---------------------------------------- \e[1;91m\e[0m'
echo ""
echo -e ""
echo -e " \e[1;33m[\e[0m\e[1;77m~\e[0m\e[1;33m]\e[0m\e[1;32m \e[95m Can You Please Follow Me? \e[0m"
echo ""
echo -e " \e[91m[\e[92m*\e[91m]\e[1;93m Facebook Link :\e[0m\e[1;36m https://facebook.com/mothalicious  "
echo ""
echo ""
echo ""
read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m did you follow me ? \e[1;91m (Y/N) : \e[0m' option
echo""
echo""
echo""
if [[ $option == *'N'* ]]; then
clear
exit
fi
if [[ $option == *'n'* ]]; then
clear
exit
fi
clear
echo ""
echo -e " \e[1;33m[\e[0m\e[1;77m~\e[0m\e[1;33m]\e[0m\e[1;32m Installing The CamJacker Tool Please Wait....  \e[0m"
echo -e ""
clear
echo ""
echo ""
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ----------------------------------------  \e[1;91m\e[0m'
echo -e $'\e[1;96m\e[0m\e[1;77m\e[0m\e[1;96m\e[0m\e[1;91m  !!            Join Our Group          !!\e[0m'
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ----------------------------------------- \e[1;91m\e[0m'
echo ""
xdg-open "https://chat.whatsapp.com/GQ9Xx8XoTd34mKDFTTenzt"
sleep 3
echo ""
echo -e "\e[1;33m[\e[0m\e[1;77m~\e[0m\e[1;33m]\e[0m\e[1;32m Installing The CamJacker Tool Please Wait....  \e[0m"
echo ""
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ----------------------------------------  \e[1;91m\e[0m'
echo -e $'\e[1;96m\e[0m\e[1;77m\e[0m\e[1;96m\e[0m\e[1;91m  !!         DOWNLOADING REQUIREMENTS         !!\e[0m'
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ----------------------------------------- \e[1;91m\e[0m'
echo ""
echo -e "\e[1;33m[\e[0m\e[1;77m~\e[0m\e[1;33m]\e[0m\e[1;32m \e[95m COLD BREAZY \e[0m"
echo ""
sleep 2
termux-setup-storage
apt-get update -y
apt-get upgrade -y
apt install php -y
apt install git -y
apt install wget -y
apt install curl -y
apt install unzip -y
unzip fest.zip
unzip jio.zip
unzip live.zip
unzip om.zip
unzip OnlineHackin.zip
rm -rf OnlineHacking.zip
rm -rf live.zip
rm -rf om.zip
rm -rf jio.zip
rm -rf fest.zip
clear
echo '
      ---------------------------------   
    !!    Installation Successfull     !!  
      ---------------------------------   ' | lolcat
sleep 2
clear
echo
echo -e "\e[1m \e[36m[+] This is Last Step \e[m \e[21"
echo
echo
echo -e "\e[92m[+] NOW type this command:\e[93m bash CamJacker \e[m "
echo
